title: Parcel B Beetle Quest
description: A choose-your-own-adventure game created around beloved experiences at Olin College of Engineering
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman